name: Bug Report
description: File a bug report
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: pull-request
    attributes:
      label: Pull Request
      description: Link to the pull request where the issue occurred
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: extra-information
    attributes:
      label: Relevant extra information
      description: Please include any relevant logs, screenshots, or other information that would be helpful in diagnosing the issue.
